#!C:\cygwin\home\bwilson\wwscc\web\installer\python\python.exe
# EASY-INSTALL-SCRIPT: 'mako==0.2.4','mako-render'
__requires__ = 'mako==0.2.4'
import pkg_resources
pkg_resources.run_script('mako==0.2.4', 'mako-render')
