#!C:\cygwin\home\bwilson\wwscc\web\installer\python\python.exe
# EASY-INSTALL-SCRIPT: 'pastescript==1.7.3','paster'
__requires__ = 'pastescript==1.7.3'
import pkg_resources
pkg_resources.run_script('pastescript==1.7.3', 'paster')
