---
# Need to specify the main docker-compose file before this file
version: '3.2'
services:
  web:
    # mount the local user's directory and create a link in the container so it uses the local copy of the web service
    build: .
    volumes: [".:/code"]
    command: "ash -c 'pip install -e /code && webserver.py'"
    environment:
      - NWRSC_DEBUG=1

