package org.wwscc.storage;
import java.io.IOException;
import java.util.List;
import org.wwscc.storage.SQLDataInterface.ResultRow;

/*** AUTOGENERATED CODE, DO NOT MODIFY ***/

public class AUTO
{
	public static String getEventVarStr()
	{
		return "ispro,practice,courses,runs,countedruns,conepen,gatepen,segments,name,date,location,sponsor,host,designer,regopened,regclosed,perlimit,totlimit,doublespecial,cost,paypal,snail,notes";
	}
	
	public static String getEventArgStr()
	{
		return "?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?";
	}
	
	public static String getEventSetStr()
	{
		return "ispro=?,practice=?,courses=?,runs=?,countedruns=?,conepen=?,gatepen=?,segments=?,name=?,date=?,location=?,sponsor=?,host=?,designer=?,regopened=?,regclosed=?,perlimit=?,totlimit=?,doublespecial=?,cost=?,paypal=?,snail=?,notes=?";
	}
	
	public static void addEventValues(org.wwscc.storage.Event o, List<Object> l)
	{
		l.add(o.ispro);
		l.add(o.ispractice);
		l.add(o.courses);
		l.add(o.runs);
		l.add(o.countedruns);
		l.add(o.conepen);
		l.add(o.gatepen);
		l.add(o.name);
		l.add(o.date);
		l.add(o.regopened);
		l.add(o.regclosed);
		l.add(o.perlimit);
		l.add(o.totlimit);
	}
	
	public static org.wwscc.storage.Driver loadDriver(ResultRow rs) throws IOException
	{
		org.wwscc.storage.Driver o = new org.wwscc.storage.Driver();
		o.driverid = rs.getUUID("driverid");
		o.firstname = rs.getString("firstname");
		o.lastname = rs.getString("lastname");
		o.alias = rs.getString("alias");
		o.email = rs.getString("email");
		o.address = rs.getString("address");
		o.city = rs.getString("city");
		o.state = rs.getString("state");
		o.zip = rs.getString("zip");
		o.phone = rs.getString("phone");
		o.brag = rs.getString("brag");
		o.sponsor = rs.getString("sponsor");
		o.membership = rs.getString("membership");
		return o;
	}
	
	public static String getDriverVarStr()
	{
		return "firstname,lastname,alias,email,address,city,state,zip,phone,brag,sponsor,membership";
	}
	
	public static String getDriverArgStr()
	{
		return "?,?,?,?,?,?,?,?,?,?,?,?";
	}
	
	public static String getDriverSetStr()
	{
		return "firstname=?,lastname=?,alias=?,email=?,address=?,city=?,state=?,zip=?,phone=?,brag=?,sponsor=?,membership=?";
	}
	
	public static void addDriverValues(org.wwscc.storage.Driver o, List<Object> l)
	{
		l.add(o.firstname);
		l.add(o.lastname);
		l.add(o.alias);
		l.add(o.email);
		l.add(o.address);
		l.add(o.city);
		l.add(o.state);
		l.add(o.zip);
		l.add(o.phone);
		l.add(o.brag);
		l.add(o.sponsor);
		l.add(o.membership);
	}
	
	public static org.wwscc.storage.DriverNote loadDriverNote(ResultRow rs) throws IOException
	{
		org.wwscc.storage.DriverNote o = new org.wwscc.storage.DriverNote();
		o.driverid = rs.getInt("driverid");
		o.notes = rs.getString("notes");
		return o;
	}
	
	public static String getDriverNoteVarStr()
	{
		return "driverid,notes";
	}
	
	public static String getDriverNoteArgStr()
	{
		return "?,?";
	}
	
	public static String getDriverNoteSetStr()
	{
		return "driverid=?,notes=?";
	}
	
	public static void addDriverNoteValues(org.wwscc.storage.DriverNote o, List<Object> l)
	{
		l.add(o.driverid);
		l.add(o.notes);
	}
	
	public static String getCarVarStr()
	{
		return "driverid,year,make,model,color,number,classcode,indexcode,tireindexed";
	}
	
	public static String getCarArgStr()
	{
		return "?,?,?,?,?,?,?,?,?";
	}
	
	public static String getCarSetStr()
	{
		return "driverid=?,year=?,make=?,model=?,color=?,number=?,classcode=?,indexcode=?,tireindexed=?";
	}
	
	public static void addCarValues(org.wwscc.storage.Car o, List<Object> l)
	{
		l.add(o.driverid);
		l.add(o.year);
		l.add(o.make);
		l.add(o.model);
		l.add(o.color);
		l.add(o.number);
		l.add(o.classcode);
		l.add(o.indexcode);
		l.add(o.tireindexed);
	}
	
	public static org.wwscc.storage.Run loadRun(ResultRow rs) throws IOException
	{
		org.wwscc.storage.Run o = new org.wwscc.storage.Run();
		o.carid = rs.getUUID("carid");
		o.eventid = rs.getInt("eventid");
		o.course = rs.getInt("course");
		o.run = rs.getInt("run");
		o.cones = rs.getInt("cones");
		o.gates = rs.getInt("gates");
		o.status = rs.getString("status");
		o.raw = rs.getDouble("raw");
		o.attr = rs.getJSON("attr");
		return o;
	}
		
	public static org.wwscc.storage.Challenge loadChallenge(ResultRow rs) throws IOException
	{
		org.wwscc.storage.Challenge o = new org.wwscc.storage.Challenge();
		o.challengeid = rs.getInt("challengeid");
		o.eventid = rs.getInt("eventid");
		o.name = rs.getString("name");
		o.depth = rs.getInt("depth");
		return o;
	}
	
	public static String getChallengeVarStr()
	{
		return "eventid,name,depth";
	}
	
	public static String getChallengeArgStr()
	{
		return "?,?,?";
	}
	
	public static String getChallengeSetStr()
	{
		return "eventid=?,name=?,depth=?";
	}
	
	public static void addChallengeValues(org.wwscc.storage.Challenge o, List<Object> l)
	{
		l.add(o.eventid);
		l.add(o.name);
		l.add(o.depth);
	}	
	
	public static org.wwscc.storage.ClassData.Class loadClass(ResultRow rs) throws IOException
	{
		org.wwscc.storage.ClassData.Class o = new org.wwscc.storage.ClassData.Class();
		o.code = rs.getString("code");
		o.descrip = rs.getString("descrip");
		o.carindexed = rs.getBoolean("carindexed");
		o.classindex = rs.getString("classindex");
		o.classmultiplier = rs.getDouble("classmultiplier");
		o.eventtrophy = rs.getBoolean("eventtrophy");
		o.champtrophy = rs.getBoolean("champtrophy");
		o.numorder = rs.getInt("numorder");
		o.countedruns = rs.getInt("countedruns");
		o.usecarflag = rs.getBoolean("usecarflag");
		o.caridxrestrict = rs.getString("caridxrestrict");
		return o;
	}
	
	public static String getClassVarStr()
	{
		return "code,descrip,carindexed,classindex,classmultiplier,eventtrophy,champtrophy,numorder,countedruns,usecarflag,caridxrestrict";
	}
	
	public static String getClassArgStr()
	{
		return "?,?,?,?,?,?,?,?,?,?,?";
	}
	
	public static String getClassSetStr()
	{
		return "code=?,descrip=?,carindexed=?,classindex=?,classmultiplier=?,eventtrophy=?,champtrophy=?,numorder=?,countedruns=?,usecarflag=?,caridxrestrict=?";
	}
	
	public static void addClassValues(org.wwscc.storage.ClassData.Class o, List<Object> l)
	{
		l.add(o.code);
		l.add(o.descrip);
		l.add(o.carindexed);
		l.add(o.classindex);
		l.add(o.classmultiplier);
		l.add(o.eventtrophy);
		l.add(o.champtrophy);
		l.add(o.numorder);
		l.add(o.countedruns);
		l.add(o.usecarflag);
		l.add(o.caridxrestrict);
	}
	
	public static org.wwscc.storage.ClassData.Index loadIndex(ResultRow rs) throws IOException
	{
		org.wwscc.storage.ClassData.Index o = new org.wwscc.storage.ClassData.Index();
		o.code = rs.getString("code");
		o.descrip = rs.getString("descrip");
		o.value = rs.getDouble("value");
		return o;
	}
	
	public static String getIndexVarStr()
	{
		return "code,descrip,value";
	}
	
	public static String getIndexArgStr()
	{
		return "?,?,?";
	}
	
	public static String getIndexSetStr()
	{
		return "code=?,descrip=?,value=?";
	}
	
	public static void addIndexValues(org.wwscc.storage.ClassData.Index o, List<Object> l)
	{
		l.add(o.code);
		l.add(o.descrip);
		l.add(o.value);
	}
	
	// EventResult	return "eventid,carid,classcode,position,courses,sum,diff,diffpoints,pospoints";
	// AnnouncerResult return "eventid,carid,classcode,lastcourse,rawdiff,netdiff,oldsum,potentialsum,olddiffpoints,potentialdiffpoints,oldpospoints,potentialpospoints,updated";	
}
