/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wwscc_storage_SqliteDatabase */

#ifndef _Included_org_wwscc_storage_SqliteDatabase
#define _Included_org_wwscc_storage_SqliteDatabase
#ifdef __cplusplus
extern "C" {
#endif
#undef org_wwscc_storage_SqliteDatabase_SQLITE_OK
#define org_wwscc_storage_SqliteDatabase_SQLITE_OK 0L
#undef org_wwscc_storage_SqliteDatabase_SQLITE_ROW
#define org_wwscc_storage_SqliteDatabase_SQLITE_ROW 100L
#undef org_wwscc_storage_SqliteDatabase_SQLITE_DONE
#define org_wwscc_storage_SqliteDatabase_SQLITE_DONE 101L
/*
 * Class:     org_wwscc_storage_SqliteDatabase
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_wwscc_storage_SqliteDatabase_init
  (JNIEnv *, jclass);

/*
 * Class:     org_wwscc_storage_SqliteDatabase
 * Method:    libversion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_wwscc_storage_SqliteDatabase_libversion
  (JNIEnv *, jclass);

/*
 * Class:     org_wwscc_storage_SqliteDatabase
 * Method:    errmsg
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_wwscc_storage_SqliteDatabase_errmsg
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_wwscc_storage_SqliteDatabase
 * Method:    open
 * Signature: (Ljava/lang/String;ZI)J
 */
JNIEXPORT jlong JNICALL Java_org_wwscc_storage_SqliteDatabase_open
  (JNIEnv *, jobject, jstring, jboolean, jint);

/*
 * Class:     org_wwscc_storage_SqliteDatabase
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_wwscc_storage_SqliteDatabase_close
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_wwscc_storage_SqliteDatabase
 * Method:    prepare
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_wwscc_storage_SqliteDatabase_prepare
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_wwscc_storage_SqliteDatabase
 * Method:    lastInsertId
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_wwscc_storage_SqliteDatabase_lastInsertId
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_wwscc_storage_SqliteDatabase
 * Method:    bind_parameter_count
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_wwscc_storage_SqliteDatabase_bind_1parameter_1count
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_wwscc_storage_SqliteDatabase
 * Method:    changes
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_wwscc_storage_SqliteDatabase_changes
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_wwscc_storage_SqliteDatabase
 * Method:    step
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_wwscc_storage_SqliteDatabase_step
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_wwscc_storage_SqliteDatabase
 * Method:    reset
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_wwscc_storage_SqliteDatabase_reset
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_wwscc_storage_SqliteDatabase
 * Method:    clear_bindings
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_wwscc_storage_SqliteDatabase_clear_1bindings
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_wwscc_storage_SqliteDatabase
 * Method:    column_count
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_wwscc_storage_SqliteDatabase_column_1count
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_wwscc_storage_SqliteDatabase
 * Method:    column_decltype
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_wwscc_storage_SqliteDatabase_column_1decltype
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_wwscc_storage_SqliteDatabase
 * Method:    column_name
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_wwscc_storage_SqliteDatabase_column_1name
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_wwscc_storage_SqliteDatabase
 * Method:    column_text
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_wwscc_storage_SqliteDatabase_column_1text
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_wwscc_storage_SqliteDatabase
 * Method:    column_blob
 * Signature: (JI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_wwscc_storage_SqliteDatabase_column_1blob
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_wwscc_storage_SqliteDatabase
 * Method:    column_double
 * Signature: (JI)D
 */
JNIEXPORT jdouble JNICALL Java_org_wwscc_storage_SqliteDatabase_column_1double
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_wwscc_storage_SqliteDatabase
 * Method:    column_long
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_wwscc_storage_SqliteDatabase_column_1long
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_wwscc_storage_SqliteDatabase
 * Method:    column_int
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_wwscc_storage_SqliteDatabase_column_1int
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_wwscc_storage_SqliteDatabase
 * Method:    bind_null
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_wwscc_storage_SqliteDatabase_bind_1null
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_wwscc_storage_SqliteDatabase
 * Method:    bind_int
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_org_wwscc_storage_SqliteDatabase_bind_1int
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     org_wwscc_storage_SqliteDatabase
 * Method:    bind_long
 * Signature: (JIJ)I
 */
JNIEXPORT jint JNICALL Java_org_wwscc_storage_SqliteDatabase_bind_1long
  (JNIEnv *, jobject, jlong, jint, jlong);

/*
 * Class:     org_wwscc_storage_SqliteDatabase
 * Method:    bind_double
 * Signature: (JID)I
 */
JNIEXPORT jint JNICALL Java_org_wwscc_storage_SqliteDatabase_bind_1double
  (JNIEnv *, jobject, jlong, jint, jdouble);

/*
 * Class:     org_wwscc_storage_SqliteDatabase
 * Method:    bind_text
 * Signature: (JILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_wwscc_storage_SqliteDatabase_bind_1text
  (JNIEnv *, jobject, jlong, jint, jstring);

/*
 * Class:     org_wwscc_storage_SqliteDatabase
 * Method:    bind_blob
 * Signature: (JI[B)I
 */
JNIEXPORT jint JNICALL Java_org_wwscc_storage_SqliteDatabase_bind_1blob
  (JNIEnv *, jobject, jlong, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
